#!/bin/bash

VERSION="v4.7.1"
#===============================================================================
# title           setup-new-computer.sh
# author          Joel Kesler 
#                 https://github.com/joelkesler
#===============================================================================
#   A shell script to help with the quick setup and installation of tools and 
#   applications for new developers at Vendasta.
# 
#   Quick Instructions:
#
#   1. Make the script executable:
#      chmod +x ./setup-new-computer.sh
#
#   2. Run the script:
#      ./setup-new-computer.sh
#
#   3. Some installs will need your password
#
#   4. You will be promted to fill out your git email and name. 
#      Use the email and name you use for Github
#
#   5. Follow the Post Installation Instructions in the Readme:
README="https://github.com/vendasta/setup-new-computer-script#post-installation-instructions"
#  
#===============================================================================


# IDEs to make availabe. Please also adjust code to brew cask install
options[0]="Visual Studio Code";    devtoolchoices[0]="+"
options[1]="Jetbrains Toolbox";     devtoolchoices[1]=""
options[2]="Pycharm";               devtoolchoices[2]=""
options[3]="Goland";                devtoolchoices[3]=""
options[4]="Webstorm";              devtoolchoices[4]=""
options[5]="Sublime Text";          devtoolchoices[5]=""
options[6]="iTerm2";                devtoolchoices[6]=""
options[7]="Cursor";                devtoolchoices[7]=""


#===============================================================================
#  Functions
#===============================================================================


printHeading() {
    printf "\n\n\n\e[0;36m$1\e[0m \n"
}

printDivider() {
    printf %"$COLUMNS"s |tr " " "-"
    printf "\n"
}

printError() {
    printf "\n\e[1;31m"
    printf %"$COLUMNS"s |tr " " "-"
    if [ -z "$1" ]      # Is parameter #1 zero length?
    then
        printf "     There was an error ... somewhere\n"  # no parameter passed.
    else
        printf "\n     Error Installing $1\n" # parameter passed.
    fi
    printf %"$COLUMNS"s |tr " " "-"
    printf " \e[0m\n"
}

printStep() {
    printf %"$COLUMNS"s |tr " " "-"
    printf "\nInstalling $1...\n";
    $2 || printError "$1"
}

printLogo() {
    # Ask user for custom ASCII text
    echo ""
    read -p 'Enter custom text for ASCII logo (or press ENTER for "vendasta"): ' custom_text
    
    # Use default if no input
    if [ -z "$custom_text" ]; then
        custom_text="vendasta"
    fi
    
    echo ""
    
    # Try to use figlet if available, otherwise fall back to simple text
    if command -v figlet &> /dev/null; then
        figlet -f standard "$custom_text"
    else
        # Fallback: Simple bordered text
        text_length=${#custom_text}
        border_length=$((text_length + 8))
        
        printf '%*s\n' "$border_length" | tr ' ' '='
        echo "    $custom_text"
        printf '%*s\n' "$border_length" | tr ' ' '='
    fi
    
    echo ""
    echo "    Q U I C K   S E T U P   S C R I P T"
    echo ""
    echo ""
    echo "    NOTE:"
    echo "    You can exit the script at any time by"
    echo "    pressing CONTROL+C a bunch"
    echo ""
}

showIDEMenuLoop() {
    # from https://serverfault.com/a/777849
    printLogo
    printHeading "Select Optional IDEs and Tools"
    printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
        echo ""
        for NUM in "${!options[@]}"; do
            echo "[""${devtoolchoices[NUM]:- }""]" $(( NUM+1 ))") ${options[NUM]}"
        done
        echo ""
}

writetoBashProfile() {
cat << EOT >> ~/.bash_profile


# --------------------------------------------------------------------
# Begin Bash autogenerated content from setup-new-computer.sh   $VERSION
# --------------------------------------------------------------------

# Supress "Bash no longer supported" message
export BASH_SILENCE_DEPRECATION_WARNING=1

# Start Homebrew
if [[ "\$(uname -p)" == "arm" ]]; then
    # Apple Silicon M1/M2 Macs
    eval "\$(/opt/homebrew/bin/brew shellenv)"
else
    # Intel Macs
    eval "\$(/usr/local/bin/brew shellenv)"
fi

# Bash Autocompletion
if type brew &>/dev/null; then
  HOMEBREW_PREFIX="\$(brew --prefix)"
  if [[ -r "\${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
    source "\${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
  else
    for COMPLETION in "\${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
      [[ -r "\$COMPLETION" ]] && source "\$COMPLETION"
    done
  fi
fi

# Google Cloud SDK
[ -e "\$(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc" ] && \
    source "\$(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc"
[ -e "\$(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc" ] && \
    source "\$(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc"

# Golang
export GOPRIVATE="github.com/vendasta"
export GOPROXY="direct"
export GO111MODULE="on"
export GOPATH=\$HOME/go
export GOBIN=\$GOPATH/bin
export PATH=\$PATH:\$GOBIN

# NVM
# This needs to be after "Setting up Path for Homebrew" to override Homebrew Node
export NVM_DIR="\$HOME/.nvm"
[ -s "\$NVM_DIR/nvm.sh" ] && \
    source "\$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "\$NVM_DIR/bash_completion" ] && \
    source "\$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Node
# Increases the default memory limit for Node, so larger Angular projects can be built
export NODE_OPTIONS=--max_old_space_size=12000

# Update Node to selected version and reinstall previous packages
node-upgrade() {
    new_version=\${1:?"Please specify a version to upgrade to. Example: node-upgrade 20"}
    nvm install "\$new_version" --reinstall-packages-from=current
    nvm alias default "\$new_version"
    # nvm uninstall "\$prev_ver"
    nvm cache clear
}

# --------------------------------------------------------------------
# End autogenerated content from setup-new-computer.sh   $VERSION
# --------------------------------------------------------------------


EOT
}

writetoZshProfile() {
cat << EOT >> ~/.zprofile


# --------------------------------------------------------------------
# Begin ZSH autogenerated content from setup-new-computer.sh   $VERSION
# --------------------------------------------------------------------

# Start Homebrew
if [[ "\$(uname -p)" == "arm" ]]; then
    # Apple Silicon M1/M2 Macs
    eval "\$(/opt/homebrew/bin/brew shellenv)"
else
    # Intel Macs
    eval "\$(/usr/local/bin/brew shellenv)"
fi

# Brew Autocompletion
if type brew &>/dev/null; then
    fpath+=\$(brew --prefix)/share/zsh/site-functions
fi

# Zsh Autocompletion
# Note: must run after Brew Autocompletion
autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit
fpath=(/usr/local/share/zsh-completions \$fpath)

# Google Cloud SDK
[ -e "\$(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc" ] && \
    source "\$(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
[ -e "\$(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc" ] && \
    source "\$(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"

# Golang
export GOPRIVATE="github.com/vendasta"
export GOPROXY="direct"
export GO111MODULE="on"
export GOPATH=\$HOME/go
export GOBIN=\$GOPATH/bin
export PATH=\$PATH:\$GOBIN

# NVM 
# This needs to be after "Setting up Path for Homebrew" to override Homebrew Node
export NVM_DIR="\$HOME/.nvm"
[ -s "\$NVM_DIR/nvm.sh" ] && \
    source "\$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "\$NVM_DIR/bash_completion" ] && \
    source "\$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Node
# Increases the default memory limit for Node, so larger Angular projects can be built
export NODE_OPTIONS=--max_old_space_size=12000

# Update Node to selected version and reinstall previous packages
node-upgrade() {
    readonly new_version=\${1:?"Please specify a version to upgrade to. Example: node-upgrade 20"}
    nvm install "\$new_version" --reinstall-packages-from=current
    nvm alias default "\$new_version"
    # nvm uninstall "\$prev_ver"
    nvm cache clear
}

# --------------------------------------------------------------------
# End autogenerated content from setup-new-computer.sh   $VERSION
# --------------------------------------------------------------------


EOT
}


writetoHuskyInit() {
cat << EOT >> ~/.config/husky/init.sh


# --------------------------------------------------------------------
# Begin Husky autogenerated content from setup-new-computer.sh   $VERSION
# --------------------------------------------------------------------

# This loads nvm.sh and sets the correct PATH before running hook

export NVM_DIR="\$HOME/.nvm"
[ -s "\$NVM_DIR/nvm.sh" ] && \
    source "\$NVM_DIR/nvm.sh"
   

# --------------------------------------------------------------------
# End autogenerated content from setup-new-computer.sh   $VERSION
# --------------------------------------------------------------------


EOT
}


#===============================================================================
# Installer: Settings
#===============================================================================


# Show IDE Selection Menu
clear
while 
    showIDEMenuLoop && \
    read -r -e -p "Enable or Disable by typing number. Hit ENTER to continue " \
    -n1 SELECTION && [[ -n "$SELECTION" ]]; \
do
    clear
    if [[ "$SELECTION" == *[[:digit:]]* && $SELECTION -ge 1 && $SELECTION -le ${#options[@]} ]]; then
        (( SELECTION-- ))
        if [[ "${devtoolchoices[SELECTION]}" == "+" ]]; then
            devtoolchoices[SELECTION]=""
        else
            devtoolchoices[SELECTION]="+"
        fi
            ERROR=" "
    else
        ERROR="Invalid option: $SELECTION"
    fi
done
printDivider


#===============================================================================
#  Installer: Essential Prerequisites  
#===============================================================================


# Install xcode cli development tools (MUST BE FIRST)
printHeading "Installing Xcode CLI Development Tools"
printDivider
    echo "Installing Xcode command line tools (required for all development)..."
    xcode-select --install && \
        read -n 1 -r -s -p $'\n\nWhen Xcode CLI tools are installed, press ANY KEY to continue...\n\n' || \
            printDivider && echo "✔ Xcode CLI tools already installed. Skipping"
printDivider


# SSH Key Setup for GitHub (SECOND - before Git operations)
printHeading "SSH Key Setup for GitHub"
printDivider
    if [ -f ~/.ssh/id_ed25519 ]; then
        echo "✔ SSH key already exists at ~/.ssh/id_ed25519"
        echo "✔ Your public key:"
        cat ~/.ssh/id_ed25519.pub
    else
        echo "Generating SSH key for GitHub..."
        read -p 'Enter your email address for SSH key: ' ssh_email
        
        # Generate SSH key
        ssh-keygen -t ed25519 -C "$ssh_email" -f ~/.ssh/id_ed25519 -N ""
        echo "✔ SSH key generated"
    fi
printDivider
    echo "✔ Starting SSH agent and adding key..."
    eval "$(ssh-agent -s)" > /dev/null 2>&1
    
    # Create SSH config if it doesn't exist
    if [ ! -f ~/.ssh/config ]; then
        echo "✔ Creating SSH config file..."
        mkdir -p ~/.ssh
        cat > ~/.ssh/config << EOF
Host github.com
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_ed25519
EOF
        echo "✔ SSH config created"
    else
        echo "✔ SSH config already exists - preserving existing configuration"
        # Check if GitHub host entry exists, if not add it safely
        if ! grep -q "Host github.com" ~/.ssh/config; then
            echo "✔ Adding GitHub SSH config to existing file..."
            cat >> ~/.ssh/config << EOF

# GitHub SSH configuration (added by setup script)
Host github.com
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_ed25519
EOF
            echo "✔ GitHub SSH config appended to existing SSH config"
        else
            echo "✔ GitHub SSH config already exists in SSH config"
        fi
    fi
printDivider
    echo "✔ Adding SSH key to SSH agent..."
    ssh-add --apple-use-keychain ~/.ssh/id_ed25519 > /dev/null 2>&1
printDivider
    echo "✔ Copying public key to clipboard..."
    pbcopy < ~/.ssh/id_ed25519.pub
    echo ""
    tput setaf 3 # yellow
    echo "🔑 IMPORTANT: Your SSH public key has been copied to clipboard!"
    echo ""
    echo "To complete GitHub setup:"
    echo "1. Go to https://github.com/settings/ssh/new"
    echo "2. Give your key a title (e.g., 'MacBook M3')"
    echo "3. Paste the key (already in clipboard)"
    echo "4. Click 'Add SSH key'"
    echo ""
    tput sgr0
    read -n 1 -r -s -p "Press any key when you've added the key to GitHub..."
    echo ""
printDivider
    echo "✔ Testing SSH connection to GitHub..."
    if ssh -T git@github.com 2>&1 | grep -q "successfully authenticated"; then
        echo "✔ SSH connection to GitHub successful!"
    else
        echo "⚠️  SSH connection test - if you just added the key, it may take a moment"
        echo "   You can test later with: ssh -T git@github.com"
    fi
printDivider


#===============================================================================
#  Installer: Set up shell profiles
#===============================================================================


# Create .bash_profile and .zprofile if they dont exist
printHeading "Prep Bash and Zsh"
printDivider
    echo "🛡️  Creating safety backups of existing shell configurations..."
    timestamp=$(date +%Y%m%d_%H%M%S)
    
    # Backup existing shell config files
    [ -f ~/.bashrc ] && cp ~/.bashrc ~/.bashrc.backup.$timestamp && echo "✔ Backed up ~/.bashrc"
    [ -f ~/.bash_profile ] && cp ~/.bash_profile ~/.bash_profile.backup.$timestamp && echo "✔ Backed up ~/.bash_profile"
    [ -f ~/.zshrc ] && cp ~/.zshrc ~/.zshrc.backup.$timestamp && echo "✔ Backed up ~/.zshrc"  
    [ -f ~/.zprofile ] && cp ~/.zprofile ~/.zprofile.backup.$timestamp && echo "✔ Backed up ~/.zprofile"
printDivider
    echo "✔ Touch ~/.bash_profile"
        touch ~/.bash_profile
printDivider
    echo "✔ Touch ~/.zprofile"
        touch ~/.zprofile
printDivider
    # Check for current version in bash profile
    if grep --quiet "setup-new-computer.sh.*$VERSION" ~/.bash_profile; then
        echo "✔ .bash_profile already has current version ($VERSION). Skipping"
    elif grep --quiet "setup-new-computer.sh" ~/.bash_profile; then
        echo "🔄 Found older version in .bash_profile. Updating to $VERSION..."
        # Remove old content and add new
        sed -i.bak "/# Begin Bash autogenerated content from setup-new-computer.sh/,/# End autogenerated content from setup-new-computer.sh/d" ~/.bash_profile
        writetoBashProfile
        echo "✔ Updated .bash_profile to $VERSION"
    else
        writetoBashProfile
        echo "✔ Added to .bash_profile"
    fi
printDivider
    # Zsh profile
    if grep --quiet "setup-new-computer.sh.*$VERSION" ~/.zprofile; then
        echo "✔ .zprofile already has current version ($VERSION). Skipping"
    elif grep --quiet "setup-new-computer.sh" ~/.zprofile; then
        echo "🔄 Found older version in .zprofile. Updating to $VERSION..."
        # Remove old content and add new
        sed -i.bak "/# Begin ZSH autogenerated content from setup-new-computer.sh/,/# End autogenerated content from setup-new-computer.sh/d" ~/.zprofile
        writetoZshProfile
        echo "✔ Updated .zprofile to $VERSION"
    else
        writetoZshProfile
        echo "✔ Added to .zprofile"
    fi
printDivider
    echo "(zsh) Rebuild zcompdump"
    rm -f ~/.zcompdump
printDivider


# Install Oh My Zsh
printHeading "Installing Oh My Zsh and Plugins"
printDivider
    if [ -d "$HOME/.oh-my-zsh" ]; then
        echo "✔ Oh My Zsh already installed. Skipping"
    else
        echo "Installing Oh My Zsh..."
        
        # CRITICAL: Backup existing .zshrc before Oh My Zsh overwrites it
        if [ -f ~/.zshrc ]; then
            echo "⚠️  Backing up existing .zshrc to .zshrc.backup.$(date +%Y%m%d_%H%M%S)"
            cp ~/.zshrc ~/.zshrc.backup.$(date +%Y%m%d_%H%M%S)
        fi
        
        # Install Oh My Zsh
        sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
        echo "✔ Oh My Zsh installed"
        
        # Restore user content if backup exists
        backup_file=$(ls -t ~/.zshrc.backup.* 2>/dev/null | head -n1)
        if [ -n "$backup_file" ] && [ -f "$backup_file" ]; then
            echo "🔧 Merging your previous .zshrc configuration..."
            # Extract user's custom content (everything not Oh My Zsh related)
            grep -v "^export ZSH=" "$backup_file" | \
            grep -v "^ZSH_THEME=" | \
            grep -v "^plugins=" | \
            grep -v "source.*oh-my-zsh" | \
            grep -v "^#.*Oh My Zsh" | \
            grep -E "^[^#]|^$" >> ~/.zshrc
            echo "✔ Your custom configurations have been preserved and merged"
            echo "📁 Original backup saved as: $backup_file"
        fi
    fi
printDivider
    echo "Installing Oh My Zsh Plugins..."
    # Install zsh-syntax-highlighting
    if [ -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting" ]; then
        echo "✔ zsh-syntax-highlighting already installed"
    else
        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
        echo "✔ zsh-syntax-highlighting installed"
    fi
    
    # Install zsh-autosuggestions
    if [ -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions" ]; then
        echo "✔ zsh-autosuggestions already installed"
    else
        git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
        echo "✔ zsh-autosuggestions installed"
    fi
    
    # Install zsh-completions
    if [ -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-completions" ]; then
        echo "✔ zsh-completions already installed"
    else
        git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-completions
        echo "✔ zsh-completions installed"
    fi
    
    # Install history-search-multi-word
    if [ -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/history-search-multi-word" ]; then
        echo "✔ history-search-multi-word already installed"
    else
        git clone https://github.com/zdharma-continuum/history-search-multi-word ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/history-search-multi-word
        echo "✔ history-search-multi-word installed"
    fi
printDivider
    echo "Installing Powerlevel10k theme..."
    # Install Powerlevel10k theme
    if [ -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k" ]; then
        echo "✔ Powerlevel10k already installed"
    else
        git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k
        echo "✔ Powerlevel10k theme installed"
    fi
printDivider
    echo "NOTE: To enable plugins, add them to your ~/.zshrc plugins list:"
    echo "plugins=(git autojump zsh-autosuggestions zsh-syntax-highlighting zsh-completions fzf web-search sudo jsontools docker history-search-multi-word)"
    echo ""
    echo "To use Powerlevel10k theme, set in your ~/.zshrc:"
    echo 'ZSH_THEME="powerlevel10k/powerlevel10k"'
    echo ""
    echo "Run 'p10k configure' after installation to customize your prompt"
printDivider


#===============================================================================
#  Installer: Main Payload
#===============================================================================


# Install Brew
printHeading "Installing Homebrew"
printDivider
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
printDivider
    echo "✔ Setting Path for Homebrew"
    echo "Path Before:"
    echo $PATH

    if [[ "$(uname -p)" == "arm" ]]; then
        # Apple Silicon M1/M2 Macs
        export PATH=/opt/homebrew/bin:$PATH
    else
        # Intel Macs
        export PATH=/usr/local/bin:$PATH
    fi
    
    echo "Path After:"
    echo $PATH
printDivider
    echo "✔ (zsh) Fix brew insecure directories warning"
    chmod go-w "$(brew --prefix)/share"
printDivider


# Install Utilities
printHeading "Installing Brew Packages"
    printStep "Bash"                        "brew install bash"
    printStep "bash-completion"             "brew install bash-completion"
    printStep "zsh-completions"             "brew install zsh-completions"
    printStep "Ruby"                        "brew install ruby"
    printStep "Git"                         "brew install git"
printDivider

printHeading "Installing Enhanced CLI Utilities"
    printStep "tree"                        "brew install tree"
    printStep "htop"                        "brew install htop"
    printStep "wget"                        "brew install wget"
    printStep "jq (JSON processor)"         "brew install jq"
    printStep "colordiff"                   "brew install colordiff"
    printStep "GitHub CLI"                  "brew install gh"
    printStep "bat (better cat)"            "brew install bat"
    printStep "fd (better find)"            "brew install fd"
    printStep "ripgrep (better grep)"       "brew install ripgrep"
    printStep "tldr (simplified man)"       "brew install tldr"
    printStep "fzf (fuzzy finder)"          "brew install fzf"
    printStep "autojump"                    "brew install autojump"
    printStep "tmux (terminal multiplexer)" "brew install tmux"
    printStep "tmuxinator (tmux manager)"   "brew install tmuxinator"
    printStep "vim (enhanced editor)"       "brew install vim"
    printStep "figlet (ASCII art text)"     "brew install figlet"
printDivider



# Install  Apps
printHeading "Installing Applications"

    if [[ -d "/Applications/Firefox.app" ]]; then
        printDivider
        echo "✔ Firefox already installed. Skipping"
    else
        printStep "Firefox"                     "brew install --cask firefox"
    fi

    if [[ -d "/Applications/Google Chrome.app" ]]; then
        printDivider
        echo "✔ Google Chrome already installed. Skipping"
    else
        printStep "Google Chrome"               "brew install --cask google-chrome"
    fi

    if [[ -d "/Applications/Chromium.app" ]]; then
        printDivider
        echo "✔ Chromium already installed. Skipping"
    else
        printStep "Chromium"                    "brew install --cask chromium"
    fi


    if [[ -d "/Applications/Brave Browser.app" ]]; then
        printDivider
        echo "✔ Brave Browser already installed. Skipping"
    else
        printStep "Brave Browser"               "brew install --cask brave-browser"
    fi

    if [[ -d "/Applications/Docker.app" ]]; then
        printDivider
        echo "✔ Docker Desktop already installed. Skipping"
    else
        printStep "Docker Desktop"                 "brew install --cask docker"
    fi


    if [[ -d "/Applications/Postman.app" ]]; then
        printDivider
        echo "✔ Postman already installed. Skipping"
    else
        printStep "Postman"                     "brew install --cask postman"
    fi

    if [[ -d "/Applications/Insomnia.app" ]]; then
        printDivider
        echo "✔ Insomnia already installed. Skipping"
    else
        printStep "Insomnia (Alternative API Client)" "brew install --cask insomnia"
    fi

    # Install Visual Studio Code
    if [[ "${devtoolchoices[0]}" == "+" ]]; then
        printStep "Visual Studio Code"      "brew install --cask visual-studio-code"
    fi
    # Install Jetbrains Toolbox
    if [[ "${devtoolchoices[1]}" == "+" ]]; then
        printStep "Jetbrains Toolbox"       "brew install --cask jetbrains-toolbox"
    fi
    # Install PyCharm
    if [[ "${devtoolchoices[2]}" == "+" ]]; then
        printStep "PyCharm"                 "brew install --cask pycharm"
    fi
    # Install Goland
    if [[ "${devtoolchoices[3]}" == "+" ]]; then
        printStep "Goland"                  "brew install --cask goland"
    fi
    # Install WebStorm
    if [[ "${devtoolchoices[4]}" == "+" ]]; then
        printStep "WebStorm"                "brew install --cask webstorm"
    fi
    # Install Sublime Text
    if [[ "${devtoolchoices[5]}" == "+" ]]; then
        printStep "Sublime Text"            "brew install --cask sublime-text"
    fi
    # Install iTerm2
    if [[ "${devtoolchoices[6]}" == "+" ]]; then
        printStep "iTerm2"                  "brew install --cask iterm2"
    fi
    # Install Cursor (AI-powered IDE)
    if [[ "${devtoolchoices[7]}" == "+" ]]; then
        printStep "Cursor"                  "brew install --cask cursor"
    fi
printDivider


# Install Productivity Applications
printHeading "Installing Productivity Applications"
    printStep "Rectangle (Window Manager)"  "brew install --cask rectangle"
    printStep "Stats (System Monitor)"      "brew install --cask stats"
    printStep "Itsycal (Menu Calendar)"     "brew install --cask itsycal"
    printStep "Calibre (Ebook Manager)"     "brew install --cask calibre"
    printStep "Notion"                      "brew install --cask notion"
    printStep "Enpass (Password Manager)"   "brew install --cask enpass"
    printStep "Meld (Diff Tool)"            "brew install --cask meld"
    printStep "Slack"                       "brew install --cask slack"
    printStep "Gitify (GitHub Notifications)" "brew install --cask gitify"
    printStep "ChatGPT"                     "brew install --cask chatgpt"
    printStep "Alfred 5"                    "brew install --cask alfred"
    printStep "Logi Options+"               "brew install --cask logi-options-plus"
printDivider


#Install Go
# TODO: check with @cpenner about current best way to install
printHeading "Installing Go"
    printDivider
        echo "✔ Creating Go directory in home folder [~/go]"
            mkdir -p ~/go
    printStep "Go"            "brew install go"
    printDivider
        echo "✔ Setting GOPRIVATE enviromental variable"
            go env -w GOPRIVATE="github.com/vendasta"
printDivider


# Install Node
printHeading "Installing Node and Angular CLI through NVM"
    printDivider
        getLastestNVM() {
            # From https://gist.github.com/lukechilds/a83e1d7127b78fef38c2914c4ececc3c
            # Get latest release from GitHub api | Get tag line | Pluck JSON value
            curl --silent "https://api.github.com/repos/nvm-sh/nvm/releases/latest" | 
                grep '"tag_name":' |
                sed -E 's/.*"([^"]+)".*/\1/'
        }
        echo "✔ Current NVM is $(getLastestNVM)"
    printDivider
        echo "Installing NVM (Node Version Manager) $(getLastestNVM)..."
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/$(getLastestNVM)/install.sh | bash
    printDivider
        echo "✔ Loading NVM into PATH"
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    printDivider
        echo "Installing Node..."
        nvm install 20
    printStep "Angular CLI"             "npm install --location=global @angular/cli"
    printStep "NX"                      "npm install --location=global nx"
    printStep "Husky"                   "npm install --location=global husky"
    printStep "Node Sass"               "npm install --location=global sass"
    printStep "Node Gyp"                "npm install --location=global node-gyp"
    printStep "Yarn"                    "npm install --location=global yarn"
    printStep "pnpm"                    "npm install --location=global pnpm"
    printStep "TypeScript"              "npm install --location=global typescript"
    printStep "ts-node"                 "npm install --location=global ts-node"
    printStep "ESLint"                  "npm install --location=global eslint"
    printStep "Prettier"                "npm install --location=global prettier"
    printStep "Nodemon"                 "npm install --location=global nodemon"
    printDivider
        echo "✔ Ensure ~/.config/husky directory exists"
            mkdir -p ~/.config/husky
    printDivider
        echo "✔ Touch ~/.config/husky/init.sh"
            touch ~/.config/husky/init.sh
    printDivider
        # Husky profile
        if grep --quiet "setup-new-computer.sh.*$VERSION" ~/.config/husky/init.sh; then
            echo "✔ ~/.config/husky/init.sh already has current version ($VERSION). Skipping"
        elif grep --quiet "setup-new-computer.sh" ~/.config/husky/init.sh; then
            echo "🔄 Found older version in ~/.config/husky/init.sh. Updating to $VERSION..."
            # Remove old content and add new
            sed -i.bak "/# Begin Husky autogenerated content from setup-new-computer.sh/,/# End autogenerated content from setup-new-computer.sh/d" ~/.config/husky/init.sh
            writetoHuskyInit
            echo "✔ Updated ~/.config/husky/init.sh to $VERSION"
        else
            writetoHuskyInit
            echo "✔ Add nvm to ~/.config/husky/init.sh"
        fi
printDivider


# Install Google Cloud SDK and Components
printHeading "Install Google Cloud SDK and Components"
    printStep "Google Cloud SDK"        "brew install --cask google-cloud-sdk"
    printDivider
        echo "✔ Prepping Autocompletes and Paths"
        source "$(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc"
        source "$(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc"
    printDivider
        if [ -e ~/google-cloud-sdk ]; then
            echo "✔ ~/google-cloud-sdk exists. Skipping"
        else
            echo "✔ Creating ~/google-cloud-sdk symlink"
            ln -s "$(brew --prefix)/Caskroom/google-cloud-sdk" ~/google-cloud-sdk &>/dev/null
            # make a convenience symlink at the install path for google-cloud-sdk when installed manually
        fi
    printStep "App Engine - Go"             "gcloud components install app-engine-go --quiet"
    printStep "App Engine - Python"         "gcloud components install app-engine-python --quiet"
    printStep "App Engine - Python Extras"  "gcloud components install app-engine-python-extras --quiet"
    printStep "Kubectl"                     "gcloud components install kubectl --quiet"
    printStep "Docker Credentials"          "gcloud components install docker-credential-gcr --quiet"
printDivider


# Install System Tweaks
printHeading "System Tweaks"
    printDivider
    echo "✔ General: Expand save and print panel by default"
        defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
        defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true
        defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
        defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true
    echo "✔ General: Save to disk (not to iCloud) by default"
        defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false
    echo "✔ General: Avoid creating .DS_Store files on network volumes"
        defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
    printDivider
        
    echo "✔ Typing: Disable smart quotes and dashes as they cause problems when typing code"
        defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
        defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
    echo "✔ Typing: Disable press-and-hold for keys in favor of key repeat"
        defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
    printDivider

    echo "✔ Finder: Show status bar and path bar"
        defaults write com.apple.finder ShowStatusBar -bool true
        defaults write com.apple.finder ShowPathbar -bool true
    echo "✔ Finder: Disable the warning when changing a file extension"
        defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
    echo "✔ Finder: Show the ~/Library folder"
        chflags nohidden ~/Library
    printDivider
        
    echo "✔ Safari: Enable Safari’s Developer Settings"
        defaults write com.apple.Safari IncludeInternalDebugMenu -bool true
        defaults write com.apple.Safari IncludeDevelopMenu -bool true
        defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
        defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true
        defaults write NSGlobalDomain WebKitDeveloperExtras -bool true
    printDivider
    
    # Note: The chrome defaults can cause your Chrome browser to display a message stating
    # that Chrome is "Managed by your organization" when it isn't
    # 
    # To view policies that are affecting this message, view the following pages:
    # chrome://policy and chrome://management/
    # 
    # To quickly remove Chrome default overrides, run the following commands:
    # defaults delete com.google.Chrome
    # defaults delete com.google.Chrome.canary
    #
    echo "✔ Chrome: Disable the all too sensitive backswipe on Trackpads and Magic Mice"
        defaults write com.google.Chrome AppleEnableSwipeNavigateWithScrolls -bool false
        defaults write com.google.Chrome.canary AppleEnableSwipeNavigateWithScrolls -bool false
        defaults write com.google.Chrome AppleEnableMouseSwipeNavigateWithScrolls -bool false
        defaults write com.google.Chrome.canary AppleEnableMouseSwipeNavigateWithScrolls -bool false
    echo "✔ Chrome: Use the system print dialog and expand dialog by default"
        defaults write com.google.Chrome DisablePrintPreview -bool true
        defaults write com.google.Chrome.canary DisablePrintPreview -bool true
        defaults write com.google.Chrome PMPrintingExpandedStateForPrint2 -bool true
        defaults write com.google.Chrome.canary PMPrintingExpandedStateForPrint2 -bool true
printDivider



#===============================================================================
#  Installer: Git
#===============================================================================


# Set up Git
printHeading "Set Up Git"

printDivider
    echo "✔ Set Git to store credentials in Keychain"
    git config --global credential.helper osxkeychain
printDivider
    if [ -n "$(git config --global user.email)" ]; then
        echo "✔ Git email is set to $(git config --global user.email)"
    else
        read -p 'What is your Git email address?: ' gitEmail
        git config --global user.email "$gitEmail"
    fi
printDivider
    if [ -n "$(git config --global user.name)" ]; then
        echo "✔ Git display name is set to $(git config --global user.name)"
    else
        read -p 'What is your Git display name (Firstname Lastname)?: ' gitName
        git config --global user.name "$gitName"
    fi
printDivider
    echo "✔ Configure git to always ssh when dealing with https github repos"
        git config --global url."git@github.com:".insteadOf https://github.com/
        # you can remove this change by editing your ~/.gitconfig file
printDivider
    echo "✔ Adding github.com to known_hosts file [~/.ssh/known_hosts]"
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
printDivider


printHeading "Installing Git Enhancement Tools"
    printStep "Git LFS"                     "brew install git-lfs"
    printStep "tig (Git browser)"           "brew install tig"
    printStep "lazygit (Git UI)"            "brew install lazygit"
printDivider


# Install Vendasta-specific Development Tools
printHeading "Installing Vendasta Development Tools"
printDivider
    echo "Installing Go development tools..."
    printStep "goimports"                   "go install golang.org/x/tools/cmd/goimports@latest"
    printStep "golangci-lint"               "go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest"
    printStep "delve (debugger)"            "go install github.com/go-delve/delve/cmd/dlv@latest"
    printStep "Vendasta CodeGen"            "go install github.com/vendasta/codegen@latest"
printDivider
    echo "✔ Go development tools installed"
    echo "NOTE: For mscli setup, clone the repository and run 'go install -mod=vendor' manually"
    echo "NOTE: For libpostal on M1 Macs, use --disable-sse2 flag during configure"
printDivider


# Install Python Development Tools
printHeading "Installing Python Development Tools"
    printStep "Anaconda (Python Distribution)" "brew install --cask anaconda"
    printStep "pyenv"                       "brew install pyenv"
    printStep "pipx (tool installer)"       "brew install pipx"
    printStep "Black (code formatter)"      "pipx install black"
    printStep "isort (import sorter)"       "pipx install isort"
    printStep "flake8 (linter)"             "pipx install flake8"
    printStep "mypy (type checker)"         "pipx install mypy"
printDivider
    echo "📋 Setting up Anaconda PATH..."
    echo "After installation, add Anaconda to your PATH:"
    echo 'export PATH="/opt/homebrew/anaconda3/bin:$PATH"  # For Apple Silicon'
    echo 'export PATH="/usr/local/anaconda3/bin:$PATH"    # For Intel Macs'
    echo ""
    echo "💡 Anaconda includes:"
    echo "   • Python with 1500+ packages"
    echo "   • Jupyter Notebook & JupyterLab" 
    echo "   • Spyder IDE"
    echo "   • conda package manager"
    echo "   • Data science libraries (pandas, numpy, matplotlib, scikit-learn)"
printDivider


# Install DevOps Tools
printHeading "Installing DevOps and Infrastructure Tools"
    printStep "Terraform"                   "brew install terraform"
    printStep "Ansible"                     "brew install ansible"
    printStep "Helm"                        "brew install helm"
    printStep "k9s (Kubernetes UI)"         "brew install k9s"
printDivider


# Install Additional Programming Languages
printHeading "Installing Additional Programming Languages"
    printStep "Rust"                        "brew install rust"
    printStep "OpenJDK (Java)"              "brew install openjdk"
printDivider


# Install Python Package Managers
printHeading "Installing Python Package Managers"
    printStep "Poetry"                      "brew install poetry"
    printStep "Pipenv"                      "brew install pipenv"
printDivider


# Install Database Tools
printHeading "Installing Database Tools"
    printStep "PostgreSQL Client"          "brew install postgresql@16"
    printStep "Redis"                       "brew install redis"
    printStep "MongoDB Tools"               "brew install mongodb/brew/mongodb-community"
printDivider


# Install Database GUI Tools
printHeading "Installing Database GUI Applications"
    printStep "DBeaver (Universal DB GUI)" "brew install --cask dbeaver-community"
    printStep "RedisInsight (Redis GUI)"    "brew install --cask redisinsight"
    printStep "MongoDB Compass"             "brew install --cask mongodb-compass"
    printStep "TablePlus (Premium DB GUI)" "brew install --cask tableplus"
printDivider


# Install Media and Document Processing Tools
printHeading "Installing Media and Document Processing Tools"
    printStep "FFmpeg"                      "brew install ffmpeg"
    printStep "ImageMagick"                 "brew install imagemagick"
    printStep "Pandoc"                      "brew install pandoc"
printDivider


#===============================================================================
#  Installer: Complete
#===============================================================================

printHeading "Setup Complete - Manual Steps Required"
printDivider

tput setaf 2 # set text color to green
cat << "EOT"

   ╭─────────────────────────────────────────────────────────────────╮
   │░░░░░░░░░░░░░░░░░░░░░░░░░░░ IMPORTANT ░░░░░░░░░░░░░░░░░░░░░░░░░░░░│
   │                                                                 │
   │          Please complete these manual steps below               │
   │                                                                 │
   └─────────────────────────────────────────────────────────────────┘

EOT
tput sgr0 # reset text

echo ""
tput bold
echo "🔧 REQUIRED MANUAL STEPS:"
tput sgr0
echo ""

echo "1. 🔄 RESTART TERMINAL"
echo "   • Close this terminal and open a new one"
echo "   • This loads all new PATH configurations"
echo ""

echo "2. 🐚 CONFIGURE ZSH SHELL"
echo "   • Edit ~/.zshrc and set theme:"
echo "     ZSH_THEME=\"powerlevel10k/powerlevel10k\""
echo ""
echo "   • Add plugins to ~/.zshrc:"
echo "     plugins=(git autojump zsh-autosuggestions zsh-syntax-highlighting"
echo "              zsh-completions fzf web-search sudo jsontools docker"
echo "              history-search-multi-word)"
echo ""
echo "   • Run: p10k configure (to customize your prompt)"
echo ""

echo "3. ✅ SSH KEYS FOR GITHUB (COMPLETED EARLY)"
echo "   • SSH keys were generated and configured at the beginning of setup"
echo "   • GitHub authentication should already be working"
echo "   • Test connection: ssh -T git@github.com"
echo ""

echo "4. ☕ CONFIGURE JAVA (if needed)"
echo "   • Add to ~/.zprofile: export JAVA_HOME=\$(/usr/libexec/java_home)"
echo "   • Restart terminal to apply"
echo ""

echo "5. 🐍 ANACONDA PATH SETUP"  
echo "   • Add to your shell profile (~/.zshrc or ~/.bash_profile):"
echo "   • For Apple Silicon: export PATH=\"/opt/homebrew/anaconda3/bin:\$PATH\""
echo "   • For Intel Macs: export PATH=\"/usr/local/anaconda3/bin:\$PATH\""
echo ""

echo "6. ☁️ GOOGLE CLOUD AUTHENTICATION"
echo "   • Run: gcloud auth application-default login"
echo "   • Required for Vendasta E2E tests"
echo ""

echo "7. 🏢 VENDASTA-SPECIFIC SETUP"
echo "   • Install libpostal (for Web-Crawler):"
echo "     git clone https://github.com/openvenues/libpostal"
echo "     cd libpostal && ./bootstrap.sh"
echo "     ./configure --datadir=~/go/src/github.com/vendasta/libpostal_data --disable-sse2"
echo "     make -j4 && sudo make install"
echo ""
echo "   • Setup mscli:"
echo "     Clone repository and run 'go install -mod=vendor'"
echo ""

echo "8. ✅ VERIFY INSTALLATIONS"
echo "   • node --version"
echo "   • go version"
echo "   • python3 --version"
echo "   • git --version"
echo ""

tput setaf 3 # yellow text
echo "📖 DOCUMENTATION LINK:"
tput sgr0
echo $README
echo ""

tput bold
echo "Press any key to open documentation in browser..."
tput sgr0
read -n 1 -r -s
open $README

echo ""
echo ""
tput setaf 2
echo "🎉 Setup script completed successfully!"
echo "   Follow the manual steps above to finish your development environment setup."
tput sgr0
echo ""


exit
