import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/installation',
        'getting-started/post-installation',
      ],
    },
    {
      type: 'category',
      label: "What's Installed",
      items: [
        'what-is-installed/shell-setup',
        'what-is-installed/command-line-tools',
        'what-is-installed/languages',
        'what-is-installed/applications',
        'what-is-installed/system-tweaks',
      ],
    },
    {
      type: 'category',
      label: 'Company-Specific Setup',
      items: ['company-specific-setup/badal-io'],
    },
    {
      type: 'category',
      label: 'Advanced Usage',
      items: [
        'advanced-usage/node-management',
        'advanced-usage/keeping-tools-updated',
      ],
    },
    {
      type: 'category',
      label: 'For Maintainers',
      items: [
        'for-maintainers/customization',
        'for-maintainers/testing',
      ],
    },
  ],
};

export default sidebars;
